//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Фабрика_ткани_WPF_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Склад_ткани
    {
        public Nullable<int> Рулон { get; set; }
        public string Артикул_ткани { get; set; }
        public Nullable<decimal> ширина { get; set; }
        public decimal длина { get; set; }
        public Nullable<int> Поставка { get; set; }
    
        public virtual Ткани Ткани { get; set; }
        public virtual Поставки Поставки { get; set; }
    }
}
